/*
=========================================================
Retail Sales SQL Project
Phase 3 : Business Analysis

Description:
This script performs business analysis on the retail sales
database using SQL queries. It answers key business
questions related to sales performance, customers,
products, stores, employees, and sales trends to
generate meaningful business insights.
=========================================================
*/

use retail;

show tables;


-- =====================================================
-- Sales KPI Analysis
-- Calculate key performance indicators (KPIs) to
-- evaluate overall business performance.
-- =====================================================

-- Business Question 1:
-- What is the total sales generated?

select sum(sales) as total_sales
from fact_sales;

-- Business Question 2:
-- How many total orders were placed?

select count(sale_id) as total_orders
from fact_sales;

-- Business Question 3:
-- How many unique customers made purchases?

select count(distinct customer_key) as total_customers
from fact_sales;

-- Business Question 4:
-- What is the average order value?

select round(avg(sales),2) as average_order_value
from fact_sales;


-- =====================================================
-- Customer Analysis
-- Analyze customer purchasing behavior and identify
-- valuable as well as inactive customers.
-- =====================================================

-- Business Question 5:
-- Identify the Top 10 Customers by Total Sales.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name
order by total_sales desc
limit 10;

-- Business Question 6:
-- Find Customers Who Have Never Placed an Order.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name
from dim_customer c
left join fact_sales f
on c.customer_key = f.customer_key
where f.customer_key is null;

-- Business Question 7:
-- Identify Repeat Customers Based on Number of Orders.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    count(f.sale_id) as total_orders
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name
having count(f.sale_id) > 1
order by total_orders desc;


-- =====================================================
-- Product Analysis
-- Evaluate product performance by analyzing sales,
-- demand, and category-wise revenue.
-- =====================================================

-- Business Question 8:
-- Which are the Top 10 best-selling products based on quantity sold?

select
    p.product_name,
    sum(f.quantity) as total_quantity
from fact_sales f
join dim_product p
on f.product_key = p.product_key
group by p.product_name
order by total_quantity desc
limit 10;

-- Business Question 9:
-- Which are the Bottom 10 products based on quantity sold?

select
    p.product_name,
    sum(f.quantity) as total_quantity
from fact_sales f
join dim_product p
on f.product_key = p.product_key
group by p.product_name
order by total_quantity
limit 10;

-- Business Question 10:
-- Which products have never been sold?

select
    p.product_key,
    p.product_name
from dim_product p
left join fact_sales f
on p.product_key = f.product_key
where f.product_key is null;

-- Business Question 11:
-- Which product categories generate the highest revenue?

select
    p.category,
    sum(f.sales) as total_sales
from fact_sales f
join dim_product p
on f.product_key = p.product_key
group by p.category
order by total_sales desc;


-- =====================================================
-- Store Analysis
-- Compare store performance based on revenue
-- and identify the best and lowest performing stores.
-- =====================================================

-- Business Question 12:
-- What is the total revenue generated by each store?

select
    s.store_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_store s
on f.store_key = s.store_key
group by s.store_name
order by total_sales desc;

-- Business Question 13:
-- Which store generates the highest revenue?

select
    s.store_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_store s
on f.store_key = s.store_key
group by s.store_name
order by total_sales desc
limit 1;

-- Business Question 14:
-- Which store generates the lowest revenue?

select
    s.store_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_store s
on f.store_key = s.store_key
group by s.store_name
order by total_sales
limit 1;


-- =====================================================
-- Employee Analysis
-- Evaluate employee sales performance and identify
-- top and low performing sales representatives.
-- =====================================================

-- Business Question 15:
-- What is the total revenue generated by each employee?

select
    e.employee_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_employee e
on f.employee_key = e.employee_key
group by e.employee_name
order by total_sales desc;

-- Business Question 16:
-- Which employee generated the highest sales?

select
    e.employee_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_employee e
on f.employee_key = e.employee_key
group by e.employee_name
order by total_sales desc
limit 1;

-- Business Question 17:
-- Which employee generated the lowest sales?

select
    e.employee_name,
    sum(f.sales) as total_sales
from fact_sales f
join dim_employee e
on f.employee_key = e.employee_key
group by e.employee_name
order by total_sales
limit 1;


-- =====================================================
-- Location Analysis
-- Analyze sales performance across different
-- geographical locations.
-- =====================================================

-- Business Question 18:
-- Which states generate the highest revenue?

select
    s.state,
    sum(f.sales) as total_sales
from fact_sales f
join dim_store s
on f.store_key = s.store_key
group by s.state
order by total_sales desc;

-- Business Question 19:
-- Which cities generate the highest revenue?

select
    s.city,
    sum(f.sales) as total_sales
from fact_sales f
join dim_store s
on f.store_key = s.store_key
group by s.city
order by total_sales desc;


-- =====================================================
-- Date & Time Analysis
-- Analyze sales trends over different time periods
-- including daily, monthly, quarterly, and yearly performance.
-- =====================================================

-- Business Question 20:
-- What are the daily sales trends?

select
    d.full_date,
    sum(f.sales) as total_sales
from fact_sales f
join dim_date d
on f.date_key = d.date_key
group by d.full_date
order by d.full_date;

-- Business Question 21:
-- What are the monthly sales trends?

select
    year(d.full_date) as year,
    month(d.full_date) as month,
    sum(f.sales) as total_sales
from fact_sales f
join dim_date d
on f.date_key = d.date_key
group by
    year(d.full_date),
    month(d.full_date)
order by
    year,
    month;

-- Business Question 22:
-- What are the quarterly sales trends?

select
    year(d.full_date) as year,
    quarter(d.full_date) as quarter,
    sum(f.sales) as total_sales
from fact_sales f
join dim_date d
on f.date_key = d.date_key
group by
    year(d.full_date),
    quarter(d.full_date)
order by
    year,
    quarter;

-- Business Question 23:
-- What are the yearly sales trends?

select
    year(d.full_date) as year,
    sum(f.sales) as total_sales
from fact_sales f
join dim_date d
on f.date_key = d.date_key
group by year(d.full_date)
order by year;


-- =====================================================
-- Invoice Analysis
-- Analyze individual sales transactions to identify
-- the highest and lowest value invoices.
-- =====================================================


-- Business Question 24:
-- Which sales transaction has the highest invoice value?

select *
from fact_sales
order by sales desc
limit 1;

-- Business Question 25:
-- Which sales transaction has the lowest invoice value?

select *
from fact_sales
order by sales
limit 1;

-- Business Question 26:
-- Which sales transaction contains the highest quantity ordered?

select *
from fact_sales
order by quantity desc
limit 1;




