/*
=========================================================
Retail Sales SQL Project
Phase 4 : Advanced SQL

Description:
This script demonstrates advanced SQL concepts
including Common Table Expressions (CTEs),
Window Functions, Views, and analytical queries
to perform advanced business analysis.
=========================================================
*/

use retail;



-- =====================================================
-- Common Table Expressions (CTEs)
-- Demonstrate the use of CTEs to simplify
-- complex analytical queries.
-- =====================================================

-- CTE Query 1:
-- Identify the Top 10 Customers Based on Total Sales.

with customer_sales as
(
    select
        c.customer_key,
        concat(c.first_name,' ',c.last_name) as customer_name,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_customer c
    on f.customer_key = c.customer_key
    group by
        c.customer_key,
        customer_name
)

select *
from customer_sales
order by total_sales desc
limit 10;


-- CTE Query 2:
-- Calculate Monthly Sales Trends.

with monthly_sales as
(
    select
        year(d.full_date) as year,
        month(d.full_date) as month,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_date d
    on f.date_key = d.date_key
    group by
        year(d.full_date),
        month(d.full_date)
)

select *
from monthly_sales
order by
    year,
    month;
    
    
-- CTE Query 3:
-- Calculate Revenue Generated by Each Product Category.

with category_sales as
(
    select
        p.category,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_product p
    on f.product_key = p.product_key
    group by p.category
)

select *
from category_sales
order by total_sales desc;


-- CTE Query 4:
-- Identify Stores with Sales Above the Overall Average.

with store_sales as
(
    select
        s.store_name,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_store s
    on f.store_key = s.store_key
    group by s.store_name
)

select *
from store_sales
where total_sales >
(
    select avg(total_sales)
    from store_sales
);


-- CTE Query 5:
-- Identify Customers Whose Total Spending is Above Average.

with customer_sales as
(
    select
        customer_key,
        sum(sales) as total_sales
    from fact_sales
    group by customer_key
)

select *
from customer_sales
where total_sales >
(
    select avg(total_sales)
    from customer_sales
)
order by total_sales desc;


-- =====================================================
-- Window Functions
-- Demonstrate ranking, running totals,
-- moving averages, and period comparisons.
-- =====================================================


-- Window Function 1:
-- Assign a Unique Row Number to Customers
-- Based on Total Sales.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    sum(f.sales) as total_sales,
    row_number() over(order by sum(f.sales) desc) as row_num
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name;


-- Window Function 2:
-- Rank Customers Based on Total Sales.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    sum(f.sales) as total_sales,
    rank() over(order by sum(f.sales) desc) as customer_rank
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name;
    
    
-- Window Function 3:
-- Assign Dense Rank to Customers
-- Based on Total Sales.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    sum(f.sales) as total_sales,
    dense_rank() over(order by sum(f.sales) desc) as customer_rank
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name;
    
    
-- Window Function 4:
-- Calculate Running Total of Monthly Sales.

with monthly_sales as
(
    select
        year(d.full_date) as year,
        month(d.full_date) as month,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_date d
    on f.date_key = d.date_key
    group by
        year(d.full_date),
        month(d.full_date)
)

select
    year,
    month,
    total_sales,
    sum(total_sales) over(
        order by year, month
    ) as running_total
from monthly_sales;


-- Window Function 5:
-- Calculate Monthly Moving Average of Sales.

with monthly_sales as
(
    select
        year(d.full_date) as year,
        month(d.full_date) as month,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_date d
    on f.date_key = d.date_key
    group by
        year(d.full_date),
        month(d.full_date)
)

select
    year,
    month,
    total_sales,
    round(
        avg(total_sales) over(
            order by year, month
        ),
        2
    ) as moving_average
from monthly_sales;


-- Window Function 6:
-- Compare Current Month Sales with Previous Month.

with monthly_sales as
(
    select
        year(d.full_date) as year,
        month(d.full_date) as month,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_date d
    on f.date_key = d.date_key
    group by
        year(d.full_date),
        month(d.full_date)
)

select
    year,
    month,
    total_sales,
    lag(total_sales) over(
        order by year, month
    ) as previous_month_sales
from monthly_sales;


-- Window Function 7:
-- Compare Current Month Sales with Next Month.

with monthly_sales as
(
    select
        year(d.full_date) as year,
        month(d.full_date) as month,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_date d
    on f.date_key = d.date_key
    group by
        year(d.full_date),
        month(d.full_date)
)

select
    year,
    month,
    total_sales,
    lead(total_sales) over(
        order by year, month
    ) as next_month_sales
from monthly_sales;


-- =====================================================
-- SQL Views
-- Create reusable virtual tables
-- for reporting and business analysis.
-- =====================================================

-- View 1:
-- Create a Customer Sales Summary View.

create view vw_customer_sales as

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    sum(f.sales) as total_sales,
    count(f.sale_id) as total_orders
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name;

-- Verify Customer Sales View

select * from vw_customer_sales;


-- View 2:
-- Create a Product Sales Summary View.

create view vw_product_sales as

select
    p.product_key,
    p.product_name,
    p.category,
    sum(f.quantity) as total_quantity,
    sum(f.sales) as total_sales
from fact_sales f
join dim_product p
on f.product_key = p.product_key
group by
    p.product_key,
    p.product_name,
    p.category;
 
-- Verify Product Sales View
 
select * from vw_product_sales;


-- View 3:
-- Create a Store Sales Summary View.

create view vw_store_sales as

select
    s.store_key,
    s.store_name,
    s.city,
    s.state,
    sum(f.sales) as total_sales
from fact_sales f
join dim_store s
on f.store_key = s.store_key
group by
    s.store_key,
    s.store_name,
    s.city,
    s.state;
    
-- Verify Store Sales View    

select * from vw_store_sales;


-- View 4:
-- Create an Employee Sales Summary View.

create view vw_employee_sales as

select
    e.employee_key,
    e.employee_name,
    e.designation,
    sum(f.sales) as total_sales
from fact_sales f
join dim_employee e
on f.employee_key = e.employee_key
group by
    e.employee_key,
    e.employee_name,
    e.designation;
  
-- Verify Employee Sales View
  
select * from vw_employee_sales;


-- View 5:
-- Create a Monthly Sales Summary View.

create view vw_monthly_sales as

select
    year(d.full_date) as year,
    month(d.full_date) as month,
    sum(f.sales) as total_sales
from fact_sales f
join dim_date d
on f.date_key = d.date_key
group by
    year(d.full_date),
    month(d.full_date);

-- Verify Monthly Sales View
    
select * from vw_monthly_sales;

-- Verify That All SQL Views Have Been Created Successfully

show full tables where table_type = 'VIEW';





