/*
=========================================================
Retail Sales SQL Project
Phase 6 : Advanced Business Analysis

Description:
This script performs advanced business analysis
using SQL to generate actionable insights related
to customer value, customer segmentation,
product performance, and revenue contribution.
=========================================================
*/

use retail;

-- =====================================================
-- Customer Lifetime Value (CLV) Analysis
-- Measure the overall value generated by each customer
-- throughout their relationship with the business.
-- =====================================================

-- Business Insight 1:
-- Calculate the Customer Lifetime Value (CLV),
-- total orders, and average order value for each customer.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,
    count(f.sale_id) as total_orders,
    sum(f.sales) as lifetime_value,
    round(avg(f.sales),2) as average_order_value
from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key
group by
    c.customer_key,
    customer_name
order by lifetime_value desc;


-- =====================================================
-- RFM (Recency, Frequency, Monetary) Analysis
-- Segment customers based on their purchasing behavior
-- to identify valuable and loyal customers.
-- =====================================================

-- Business Insight 2:
-- Calculate Recency, Frequency, and Monetary values
-- for each customer.

select
    c.customer_key,
    concat(c.first_name,' ',c.last_name) as customer_name,

    datediff(
        (select max(full_date) from dim_date),
        max(d.full_date)
    ) as recency,

    count(f.sale_id) as frequency,

    round(sum(f.sales),2) as monetary

from fact_sales f
join dim_customer c
on f.customer_key = c.customer_key

join dim_date d
on f.date_key = d.date_key

group by
    c.customer_key,
    customer_name

order by monetary desc;


-- =====================================================
-- Pareto (80/20) Analysis
-- Identify products contributing the highest percentage
-- of total sales using the Pareto Principle.
-- =====================================================

-- Business Insight 3:
-- Determine cumulative sales contribution of products
-- to identify high-impact products.

with product_sales as
(
    select
        p.product_key,
        p.product_name,
        sum(f.sales) as total_sales
    from fact_sales f
    join dim_product p
    on f.product_key = p.product_key
    group by
        p.product_key,
        p.product_name
),

sales_summary as
(
    select
        product_key,
        product_name,
        total_sales,
        sum(total_sales) over(order by total_sales desc) as cumulative_sales,
        sum(total_sales) over() as overall_sales
    from product_sales
)

select
    product_key,
    product_name,
    total_sales,
    round((total_sales / overall_sales) * 100,2) as sales_percentage,
    round((cumulative_sales / overall_sales) * 100,2) as cumulative_percentage
from sales_summary
order by total_sales desc;


-- =====================================================
-- Category Sales Contribution Analysis
-- Measure the percentage contribution of each
-- product category to the overall business revenue.
-- =====================================================

-- Business Insight 4:
-- Calculate category-wise revenue contribution
-- as a percentage of total sales.

select
    p.category,
    sum(f.sales) as total_sales,
    round(
        (sum(f.sales) / (select sum(sales) from fact_sales)) * 100,
        2
    ) as sales_contribution_percentage
from fact_sales f
join dim_product p
on f.product_key = p.product_key
group by p.category
order by total_sales desc;










